"""
Definition of the 3 CrewAI agents of the self-healing crew.

Each agent has a specific role in the CI/CD repair cycle:
  1. log-analyst  — Root cause analyst (RCA) of the CI failure.
  2. fix-engineer — Solution engineering: generates the patch.
  3. reviewer     — Validates the patch BEFORE it is applied.

All agents use the same Amazon Bedrock LLM configured with low temperature
for higher determinism and reproducibility.
"""

from __future__ import annotations

import logging

from crewai import Agent, LLM

from crew.config import Settings

logger = logging.getLogger(__name__)


def build_llm(settings: Settings) -> LLM:
    """Builds the CrewAI LLM object pointing to Amazon Bedrock via LiteLLM.

    In Fargate, credentials come from the Task IAM role (no hardcoded keys).
    Locally, the configured AWS profile credentials are used.

    Args:
        settings: Validated crew configuration.

    Returns:
        LLM instance ready to assign to agents.
    """
    logger.debug(
        "Configuring LLM: model=%s region=%s temperature=%.2f",
        settings.bedrock_model_id,
        settings.aws_region,
        settings.llm_temperature,
    )
    return LLM(
        model=settings.bedrock_model_id,
        temperature=settings.llm_temperature,
        # LiteLLM takes the region from the AWS_REGION environment variable
        # which is already set in the Fargate Task Definition.
        # We pass aws_region_name as an explicit fallback.
        aws_region_name=settings.aws_region,
    )


def build_agents(settings: Settings) -> tuple[Agent, Agent, Agent]:
    """Builds and returns the 3 crew agents.

    Returns:
        Tuple (log_analyst, fix_engineer, reviewer).
    """
    llm = build_llm(settings)

    # ── 1. Log analyst ────────────────────────────────────────────────────────
    log_analyst = Agent(
        role="CI Log Analyst",
        goal=(
            "Identify the exact root cause of the CI/CD failure from the "
            "execution log. Produce a structured diagnosis that includes: "
            "(1) error type, (2) affected file and line if applicable, "
            "(3) probable cause, (4) relevant log context."
        ),
        backstory=(
            "You are a senior platform engineer specialized in CI/CD pipeline "
            "diagnosis. You have analyzed thousands of GitHub Actions, Jenkins, "
            "and GitLab CI logs. You have deep expertise in TypeScript/Node.js "
            "compilation failures, unit tests, linting, CDK synthesis, and Docker "
            "errors. You are methodical, precise, and never assume causes without "
            "evidence in the log. You always cite the exact line that confirms "
            "your diagnosis."
        ),
        llm=llm,
        verbose=False,
        allow_delegation=False,
        max_iter=3,
        max_retry_limit=2,
    )

    # ── 2. Fix engineer ───────────────────────────────────────────────────────
    fix_engineer = Agent(
        role="CI Repair Engineer",
        goal=(
            "Generate a precise and minimal patch that resolves the root cause "
            "identified by the log analyst. The patch must: "
            "(1) be as small as possible (principle of minimal intervention), "
            "(2) not break other parts of the code, "
            "(3) return the COMPLETE corrected file content (not just changed lines) "
            "in the required format with FILE_PATH and <<<FILE_CONTENT>>> markers, "
            "(4) include a JUSTIFICATION explaining why the change resolves the root cause."
        ),
        backstory=(
            "You are a full-stack software engineer with expertise in regression "
            "repair and technical debt. You are deeply familiar with the "
            "TypeScript/Node.js, Python, AWS CDK, and ESP-IDF ecosystems. "
            "When generating a patch you always think about side effects and "
            "prioritize surgical changes over broad refactors. "
            "You never introduce new dependencies without explicit justification. "
            "You always return the COMPLETE corrected file content (every line of the file) "
            "wrapped in <<<FILE_CONTENT>>> ... <<<END_FILE_CONTENT>>> markers, "
            "because the system applies your output directly via the GitHub Contents API "
            "— it does NOT parse diffs. Modifying only the lines strictly needed to fix "
            "the root cause, leaving all other lines unchanged."
        ),
        llm=llm,
        verbose=False,
        allow_delegation=False,
        max_iter=3,
        max_retry_limit=2,
    )

    # ── 3. Reviewer ───────────────────────────────────────────────────────────
    reviewer = Agent(
        role="CI Patch Reviewer",
        goal=(
            "Validate the patch generated by the repair engineer and emit "
            "a structured verdict. The verdict must be exactly: "
            "'VERDICT: APPLY' if the patch is correct and safe, or "
            "'VERDICT: REJECT' with the reason if it has issues. "
            "The verdict must appear on the last line of the response."
        ),
        backstory=(
            "You are a senior code reviewer focused on security and quality. "
            "Before approving an AI-generated patch you verify: "
            "(1) that the patch actually resolves the identified root cause, "
            "(2) that it does not introduce security vulnerabilities, "
            "(3) that it respects project conventions, "
            "(4) that the diff is syntactically correct and applicable, "
            "(5) that it does not modify protected branches (main/master). "
            "You are skeptical by nature: if in doubt, you reject."
        ),
        llm=llm,
        verbose=False,
        allow_delegation=False,
        max_iter=2,
        max_retry_limit=1,
    )

    logger.info(
        "Agents built: log_analyst, fix_engineer, reviewer "
        "(model=%s)",
        settings.bedrock_model_id,
    )
    return log_analyst, fix_engineer, reviewer
